export const SIGNIN = 'SIGNIN';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNOUT = 'SIGNOUT';
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS';
export const SET_AUTH_STATUS = 'SET_AUTH_STATUS';
export const SIGNIN_WITH_GOOGLE = 'SIGNIN_WITH_GOOGLE';
export const ON_AUTHSTATE_CHANGED = 'ON_AUTHSTATE_CHANGED';
export const SET_AUTH_PERSISTENCE = 'SET_AUTH_PERSISTENCE';
export const ON_AUTHSTATE_SUCCESS = 'ON_AUTHSTATE_SUCCESS';
export const ON_AUTHSTATE_FAIL = 'ON_AUTHSTATE_FAIL';


export const LOADING = 'LOADING';
export const IS_AUTHENTICATING = 'IS_AUTHENTICATING';
export const SET_REQUEST_STATUS = 'SET_REQUEST_STATUS';

export const GET_ARTICLES = 'GET_ARTICLES';
export const GET_ARTICLES_SUCCESS = 'GET_ARTICLES_SUCCESS';
export const ADD_ARTICLE = 'ADD_ARTICLE';
export const ADD_ARTICLE_SUCCESS = 'ADD_ARTICLE_SUCCESS';
export const REMOVE_ARTICLE = 'REMOVE_ARTICLE';
export const REMOVE_ARTICLE_SUCCESS = 'REMOVE_ARTICLE_SUCCESS';
export const EDIT_ARTICLE = 'EDIT_ARTICLE';
export const EDIT_ARTICLE_SUCCESS = 'EDIT_ARTICLE_SUCCESS';
export const CANCEL_GET_ARTICLES = 'CANCEL_GET_ARTICLES';

export const GET_TALES_COLLECTIONS = 'GET_TALES_COLLECTIONS';
export const GET_TALES_COLLECTIONS_SUCCESS = 'GET_TALES_COLLECTIONS_SUCCESS';
export const ADD_TALES_COLLECTION = 'ADD_TALES_COLLECTION';
export const ADD_TALES_COLLECTION_SUCCESS = 'ADD_TALES_COLLECTION_SUCCESS';
export const REMOVE_TALES_COLLECTION = 'REMOVE_TALES_COLLECTION';
export const REMOVE_TALES_COLLECTION_SUCCESS = 'REMOVE_TALES_COLLECTION_SUCCESS';
export const EDIT_TALES_COLLECTION = 'EDIT_TALES_COLLECTION';
export const EDIT_TALES_COLLECTION_SUCCESS = 'EDIT_TALES_COLLECTION_SUCCESS';
export const CANCEL_GET_TALES_COLLECTIONS = 'CANCEL_GET_TALES_COLLECTIONS';

export const GET_TALES_ARTICLES = 'GET_TALES_ARTICLES';
export const GET_TALES_ARTICLES_SUCCESS = 'GET_TALES_ARTICLES_SUCCESS';
export const ADD_TALES_ARTICLE = 'ADD_TALES_ARTICLE';
export const ADD_TALES_ARTICLE_SUCCESS = 'ADD_TALES_ARTICLE_SUCCESS';
export const REMOVE_TALES_ARTICLE = 'REMOVE_TALES_ARTICLE';
export const REMOVE_TALES_ARTICLE_SUCCESS = 'REMOVE_TALES_ARTICLE_SUCCESS';
export const EDIT_TALES_ARTICLE = 'EDIT_TALES_ARTICLE';
export const EDIT_TALES_ARTICLE_SUCCESS = 'EDIT_TALES_ARTICLE_SUCCESS';
export const CANCEL_GET_TALES_ARTICLES = 'CANCEL_GET_TALES_ARTICLES';